WebStore/Models/Categoria.cs
using System.ComponentModel.DataAnnotations;

namespace WebStore.Models
{
    public class Categoria
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage ="Nombre de Categoria es obligatorio.")]
        public string? NombreCategoria { get; set; }

        [Required(ErrorMessage ="Orden es obligatorio.")]
        [Range(1, int.MaxValue, ErrorMessage ="El Orden debe ser mayor a cero.")]
        public int MostrarOrden { get; set; }
    }
}

WebStore/Models/ErrorViewModel.cs
namespace WebStore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebStore/Models/TipoAplicacion.cs
using System.ComponentModel.DataAnnotations;

namespace WebStore.Models
{
    public class TipoAplicacion
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Nombre de Tipo de Aplicacion es obligatorio.")]
        public string? Nombre { get; set; }
    }
}

WebStore/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Datos;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriaController(ApplicationDbContext db)
        {
            _context = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Categoria> lista = _context.Categorias;
            return View(lista);
        }
        //Get
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crear(Categoria categoria)
        {
            if (!ModelState.IsValid) { return View(categoria); }

            _context.Categorias.Add(categoria);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        //Get Editar
        public IActionResult Editar(int? Id)
        {
            if (Id == null || Id == 0) {  return NotFound(); }

            var obj = _context.Categorias.Find(Id);
            if (obj == null) { return NotFound(); }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(Categoria categoria)
        {
            if (!ModelState.IsValid) { return View(categoria); }

            _context.Categorias.Update(categoria);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        //Get Eliminar
        public IActionResult Eliminar(int? Id)
        {
            if (Id == null || Id == 0) { return NotFound(); }

            var obj = _context.Categorias.Find(Id);
            if (obj == null) { return NotFound(); }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Eliminar(Categoria categoria)
        {
            if (categoria == null) { return NotFound(); }

            _context.Categorias.Remove(categoria);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebStore/Controllers/TipoAplicacionController.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Datos;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class TipoAplicacionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TipoAplicacionController(ApplicationDbContext db)
        {
            _context = db;
        }
        public IActionResult Index()
        {
            IEnumerable<TipoAplicacion> lista = _context.TipoAplicaciones;
            return View(lista);
        }
        //Get
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crear(TipoAplicacion tipoAplicacion)
        {
            if (!ModelState.IsValid) { return View(tipoAplicacion); }

            _context.TipoAplicaciones.Add(tipoAplicacion);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        //Get Editar
        public IActionResult Editar(int? Id)
        {
            if (Id == null || Id == 0) { return NotFound(); }

            var obj = _context.TipoAplicaciones.Find(Id);
            if (obj == null) { return NotFound(); }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(TipoAplicacion tipoAplicacion)
        {
            if (!ModelState.IsValid) { return View(tipoAplicacion); }

            _context.TipoAplicaciones.Update(tipoAplicacion);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        //Get Eliminar
        public IActionResult Eliminar(int? Id)
        {
            if (Id == null || Id == 0) { return NotFound(); }

            var obj = _context.TipoAplicaciones.Find(Id);
            if (obj == null) { return NotFound(); }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Eliminar(TipoAplicacion tipoAplicacion)
        {
            if (tipoAplicacion == null) { return NotFound(); }

            _context.TipoAplicaciones.Remove(tipoAplicacion);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebStore/Views/Categoria/Crear.cshtml
@model Categoria

@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Crear">
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger">

        </div>

        <div class="form-group row">
            <h2 class="text-info pl-3">Nueva Categoria</h2>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreCategoria" class="form-label">Nombre Categoria</label>
                    <input asp-for="NombreCategoria" class="form-control"/>
                    <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="MostrarOrden" class="form-label">Orden</label>
                    <input asp-for="MostrarOrden" class="form-control" />
                    <span asp-validation-for="MostrarOrden" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Crear Nueva</button>
                <a asp-controller="Categoria" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

WebStore/Views/Categoria/Editar.cshtml
@model Categoria

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Editar">
    <input asp-for="Id" hidden/>
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>

        <div class="form-group row">
            <h2 class="text-info pl-3">Editar Categoria</h2>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreCategoria" class="form-label">Nombre Categoria</label>
                    <input asp-for="NombreCategoria" class="form-control" />
                    <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="MostrarOrden" class="form-label">Orden</label>
                    <input asp-for="MostrarOrden" class="form-control"/>
                    <span asp-validation-for="MostrarOrden" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Actualizar</button>
                <a asp-controller="Categoria" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WebStore/Views/Categoria/Eliminar.cshtml
@model Categoria

@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Eliminar">
    <input asp-for="Id" hidden />
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>

        <div class="form-group row">
            <h2 class="text-danger pl-3">Esta seguro de eliminar la Categoria?</h2>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreCategoria" class="form-label">Nombre Categoria</label>
                    <input asp-for="NombreCategoria" disabled class="form-control" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="MostrarOrden" class="form-label">Orden</label>
                    <input asp-for="MostrarOrden" disabled class="form-control"/>
                </div>
            </div>

            <br />

            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a asp-controller="Categoria" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WebStore/Views/Categoria/Index.cshtml
@model IEnumerable<Categoria>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Lista de Categorias</h2>
        </div>

        <div class="col-6 text-end">
            <a asp-controller="Categoria" asp-action="Crear" class="btn btn-primary">
                <i class="fa-solid fa-plus"></i> Nueva Categoria
            </a>
        </div>
    </div>

    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Nombre Categoria</th>
                    <th>Orden</th>
                    <th>

                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th width="50%"> @item.NombreCategoria </th>
                        <th width="30%"> @item.MostrarOrden </th>
                        <th class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Categoria" asp-action="Editar" asp-route-Id="@item.Id" class="btn btn-primary mx-2">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                                <a asp-controller="Categoria" asp-action="Eliminar" asp-route-Id="@item.Id" class="btn btn-danger mx-2">
                                    <i class="fa-solid fa-trash"></i>
                                </a>
                            </div>

                        </th>
                    </tr>
                }
            </tbody>

        </table>
    }
    else
    {
        <p class="text-danger">No hay registros de Categoria</p>
    }

</div>

WebStore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoAplicacion" asp-action="Index">Tipo de Aplicacion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebStore/Views/TipoAplicacion/Crear.cshtml
@model TipoAplicacion

@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Crear">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Nueva Tipo de Aplicacion</h2>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Nombre" class="form-label">Nombre de Aplicacion</label>
                    <input asp-for="Nombre" class="form-control" />
                </div>
            </div>

            <br />

            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Crear Nueva</button>
                <a asp-controller="TipoAplicacion" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

WebStore/Views/TipoAplicacion/Editar.cshtml
@model TipoAplicacion

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Editar">
    <input asp-for="Id" hidden/>
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>

        <div class="form-group row">
            <h2 class="text-info pl-3">Editar Tipo de Aplicacion</h2>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Nombre" class="form-label">Nombre Tipo de Aplicacion</label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Actualizar</button>
                <a asp-controller="TipoAplicacion" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WebStore/Views/TipoAplicacion/Eliminar.cshtml
@model TipoAplicacion

@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Eliminar">
    <input asp-for="Id" hidden />
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>

        <div class="form-group row">
            <h2 class="text-danger pl-3">Esta seguro de eliminar el Tipo de Aplicacion?</h2>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Nombre" class="form-label">Nombre Tipo de Aplicacion</label>
                    <input asp-for="Nombre" disabled class="form-control" />
                </div>
            </div>

            <br />

            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a asp-controller="TipoAplicacion" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WebStore/Views/TipoAplicacion/Index.cshtml
@model IEnumerable<TipoAplicacion>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Lista de Tipo de Aplicacion</h2>
        </div>

        <div class="col-6 text-end">
            <a asp-controller="TipoAplicacion" asp-action="Crear" class="btn btn-primary">
                <i class="fa-solid fa-plus"></i> Nuevo Tipo de Aplicacion
            </a>
        </div>
    </div>

    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Nombre Tipo Aplicacion</th>
                    <th>

                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th width="50%"> @item.Nombre </th>
                        <th class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="TipoAplicacion" asp-action="Editar" asp-route-Id="@item.Id" class="btn btn-primary mx-2">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                                <a asp-controller="TipoAplicacion" asp-action="Eliminar" asp-route-Id="@item.Id" class="btn btn-danger mx-2">
                                    <i class="fa-solid fa-trash"></i>
                                </a>
                            </div>

                        </th>
                    </tr>
                }
            </tbody>

        </table>
    }
    else
    {
        <p class="text-danger">No hay registros de Tipo de Aplicacion</p>
    }

</div>